import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import { getAuth, signInWithEmailAndPassword, signOut, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';
import { getFirestore, collection, doc, getDocs, getDoc, setDoc, addDoc, deleteDoc, writeBatch, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js';
import { firebaseConfig } from './firebase-config.js';

const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
const db = getFirestore(app);

const FIELDS = [
  ['specManagementId','商品規格管理編號','text','import'],['productManagementId','商品管理編號','text','import'],['title','商品標題','text','import'],
  ['spec1','規格1','text','import'],['spec2','規格2','text','import'],['spec3','規格3','text','import'],['note','備註','textarea','editable'],
  ['taiwanUrl','台灣URL','url','import'],['japanUrl','日本URL','url','import'],['storeCode','店鋪編號','text','calculated'],['storeName','店鋪名','text','calculated'],
  ['active','上架','boolean','editable'],['priceJPY','日幣售價(JPY)','number','editable'],['weightG','重量(g)','number','editable'],
  ['productCostTWD','商品成本(TWD)','number','calculated'],['domesticShippingJPY','日本國內運費(JPY)','number','calculated'],['domesticShippingTWD','日本國內運費(TWD)','number','calculated'],['logisticsMethod','物流方式','text','calculated'],
  ['uniCostTWD','統一成本(TWD)','number','calculated'],['nisshinCostTWD','新日誠成本(TWD)','number','calculated'],['fixedLogisticsCostTWD','固定規則物流成本(TWD)','number','calculated'],
  ['manualPriceTWD','商品台幣售價(手動)','number','calculated'],['customerShippingTWD','客收運費(TWD)','number','calculated'],['grossReceivedTWD','原實收(TWD)','number','calculated'],
  ['platformFeeTWD','平台費(TWD)','number','calculated'],['profitTWD','利潤(TWD)','number','calculated'],['profitRate','利潤率','percent','calculated'],
  ['suggestedPrice30TWD','30%利潤建議售價(TWD)','number','calculated'],['pageViews','頁面檢視總數','number','import'],['unitsSold','銷售商品數','number','import'],
  ['orderCount','銷售訂單數','number','import'],['conversionRate','轉換率','percent','calculated']
];
const FIELD_MAP = Object.fromEntries(FIELDS.map(f=>[f[0],{key:f[0],label:f[1],type:f[2],mode:f[3]}]));
const IMPORT_ALIASES = {
  specManagementId:['商品規格管理編號','SKU','sku'], productManagementId:['商品管理編號','商品編號'], title:['商品標題','商品名稱','商品名'],
  spec1:['規格1'], spec2:['規格2'], spec3:['規格3'], note:['備註'], taiwanUrl:['商品網址','台灣URL','台灣網址'], japanUrl:['店鋪網址','日本URL','日本網址'],
  priceJPY:['日幣售價(JPY)','日幣售價','售價'], weightG:['重量(g)','重量'], pageViews:['頁面檢視','頁面檢視總數','頁面檢視總數/月'],
  unitsSold:['售出單位','銷售商品數','銷售數'], orderCount:['訂單計數','銷售訂單數']
};
const DEFAULT_PARAMS = { productCostRate:.2, freeDomesticJPY:3980, domesticShippingJPY:800, platformFeeRate:.12, targetProfitRate:.3, customerShippingPerKgTWD:199, freeShippingTWD:5000, uniFirstKgTWD:205, uniEachHalfKgTWD:102.5, nisshinRate:.2, nisshinDiscount:.85, nisshinFixedFeeTWD:82, tiers:[[.5,1450],[.6,1600],[.7,1750],[.8,1900],[.9,2050],[1,2200],[1.25,2500],[1.5,2800],[1.75,3100],[2,3400],[2.5,3900],[3,4400],[3.5,4900],[4,5400],[4.5,5900],[5,6400],[5.5,6900],[6,7400],[7,8200],[8,9000],[9,9800],[10,10600],[11,11400],[12,12200],[13,13000]] };
const PARAM_DEFS = [['productCostRate','商品成本匯率'],['freeDomesticJPY','日本國內免運門檻(JPY)'],['domesticShippingJPY','預設日本國內運費(JPY)'],['platformFeeRate','平台費率'],['targetProfitRate','目標利潤率'],['customerShippingPerKgTWD','客收運費/公斤(TWD)'],['freeShippingTWD','台幣免運門檻(TWD)'],['uniFirstKgTWD','統一數網首重1kg(TWD)'],['uniEachHalfKgTWD','統一數網續重0.5kg(TWD)'],['nisshinRate','新日誠物流匯率'],['nisshinDiscount','新日誠物流折扣'],['nisshinFixedFeeTWD','新日誠物流固定作業費(TWD)']];
const PLATFORMS=[{id:'taiwan_rakuten',name:'台灣樂天'},{id:'rianyou_shopify',name:'日安優物 Shopify'}];
const MAINT_COLLECTIONS={products:'商品主檔',sales:'銷售',ads:'廣告',productAnalysis:'商品分析',imports:'匯入紀錄',platforms:'平台資料',stores:'店鋪資料'};
const DEFAULT_COLUMNS=['specManagementId','productManagementId','title','storeCode','taiwanUrl','japanUrl','active','priceJPY','domesticShippingJPY','domesticShippingTWD','weightG','manualPriceTWD','profitTWD','profitRate'];
const SALES_COLUMNS=['specManagementId','productManagementId','title','storeCode','active','pageViews','unitsSold','orderCount','conversionRate','manualPriceTWD','profitTWD','profitRate'];
let products=[], stores=[], storeMap=new Map(), params={...DEFAULT_PARAMS}, visibleColumns=JSON.parse(localStorage.getItem('visibleColumns')||'null')||DEFAULT_COLUMNS, page=1; const PAGE_SIZE=50;
let currentView='products', selectedProductIds=new Set(), discountResults=[];
let sortState={key:'',direction:'asc'}, columnFilters={}, activeFilterKey='';
const $=id=>document.getElementById(id); const n=v=>Number(v)||0; const round=v=>Math.round(v); const ceilKg=g=>Math.ceil(n(g)/1000);
function toast(msg){$('toast').textContent=msg;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),2800)}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function cleanText(v){return String(v??'').replace(/\u00a0/g,' ').replace(/\u3000/g,' ').replace(/[\r\n\t]+/g,' ').trim()}
function cleanHeader(v){return cleanText(v).replace(/\s+/g,'').replace(/[（]/g,'(').replace(/[）]/g,')')}
function cleanNumber(v){if(v===null||v===undefined||v==='')return null;const s=String(v).replace(/[¥￥$,，\s]/g,'').replace(/[^0-9.\-]/g,'');return s===''?null:Number(s)}
function validUrl(v){const s=cleanText(v);if(!s)return '';try{return new URL(s).href}catch{return /^www\./i.test(s)?`https://${s}`:''}}
function extractStoreCode(...values){for(const value of values){const s=cleanText(value).toUpperCase();const m=s.match(/(?:^|[^A-Z0-9])(R\d{1,4})(?=[^A-Z0-9]|$)/i)||s.match(/^(R\d{1,4})/i);if(m)return m[1].toUpperCase()}return ''}
function getStore(base){const code=extractStoreCode(base.storeCode,base.productManagementId,base.specManagementId);return code?storeMap.get(code):null}
function compute(base){
  const p={...base}, ov=p.overrides||{}, price=n(p.priceJPY), weight=n(p.weightG), store=getStore(p);
  const storeCode=store?.code||extractStoreCode(p.storeCode,p.productManagementId,p.specManagementId);
  const storeName=store?.name||p.storeName||'';
  const japanUrl=validUrl(p.japanUrl)||validUrl(store?.url)||'';
  const productCost=price?price*params.productCostRate:null;
  const domesticJPY=price?(price>=params.freeDomesticJPY?0:n(store?.shippingJPY)||params.domesticShippingJPY):null;
  const domestic=domesticJPY===null?null:domesticJPY*params.productCostRate;
  const method=weight?(weight<=600?'統一':'新日誠'):'';
  const uni=weight?(weight<=1000?params.uniFirstKgTWD:params.uniFirstKgTWD+Math.ceil((weight-1000)/500)*params.uniEachHalfKgTWD):null;
  let nisshin=null;if(weight){const kg=weight/1000;if(kg>13)nisshin='超重';else{const tier=params.tiers.find(([max])=>kg<=max);nisshin=tier?round(tier[1]*params.nisshinRate*params.nisshinDiscount+params.nisshinFixedFeeTWD):null}}
  const fixed=method==='統一'?uni:nisshin;
  const suggested=price?calcSuggested(productCost,domestic,fixed,weight):null;
  const manual=ov.manualPriceTWD?n(p.manualPriceTWD):suggested;
  const customer=manual!==null?(manual>=params.freeShippingTWD?0:ceilKg(weight)*params.customerShippingPerKgTWD):null;
  const gross=manual!==null?manual+customer:null;
  const fee=manual!==null?manual*params.platformFeeRate:null;
  const profit=gross!==null&&typeof fixed==='number'?gross-fee-fixed-productCost-domestic:null;
  const margin=gross?profit/gross:null;
  const conversion=n(p.pageViews)>0?n(p.orderCount)/n(p.pageViews):null;
  const values={storeCode,storeName,japanUrl,productCostTWD:productCost,domesticShippingJPY:domesticJPY,domesticShippingTWD:domestic,logisticsMethod:method,uniCostTWD:uni,nisshinCostTWD:nisshin,fixedLogisticsCostTWD:fixed,manualPriceTWD:manual,customerShippingTWD:customer,grossReceivedTWD:gross,platformFeeTWD:fee,profitTWD:profit,profitRate:margin,suggestedPrice30TWD:suggested,conversionRate:conversion};
  Object.keys(values).forEach(k=>{if(ov[k])values[k]=p[k]});return {...p,...values};
}
function calcSuggested(j,k,o,weight){const target=params.targetProfitRate,denom=1-params.platformFeeRate-target;if(denom<=0)return null;const ship=ceilKg(weight)*params.customerShippingPerKgTWD;const candidate=((n(j)+n(k)+n(o))-ship*(1-target))/denom;return round(candidate>=params.freeShippingTWD?(n(j)+n(k)+n(o))/denom:candidate)}
function formatInteger(v){const value=Number(v);return Number.isFinite(value)?Math.round(value).toLocaleString('zh-TW'):esc(v)}
function format(k,v){const t=FIELD_MAP[k]?.type;if(v===null||v===undefined||v==='')return '';if(t==='url'){const url=validUrl(v);return url?`<a class="url-link" href="${esc(url)}" target="_blank" rel="noopener noreferrer">開啟 ↗</a>`:''}if(t==='percent')return(n(v)*100).toFixed(1)+'%';if(t==='number')return formatInteger(v);if(t==='boolean')return v?'<span class="badge">上架</span>':'<span class="badge off">下架</span>';return esc(v)}
async function ensurePlatforms(){for(const x of PLATFORMS)await setDoc(doc(db,'platforms',x.id),{name:x.name,active:true,updatedAt:serverTimestamp()},{merge:true})}
async function loadStores(){const snap=await getDocs(collection(db,'stores'));stores=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>String(a.code).localeCompare(String(b.code),undefined,{numeric:true}));storeMap=new Map(stores.map(s=>[String(s.code||s.id).toUpperCase(),s]))}
async function loadAll(){await ensurePlatforms();const setting=await getDoc(doc(db,'settings','params'));params=setting.exists()?{...DEFAULT_PARAMS,...setting.data()}:structuredClone(DEFAULT_PARAMS);await loadStores();const snap=await getDocs(collection(db,'products'));products=snap.docs.map(d=>({id:d.id,...d.data()})).map(compute);renderAll();renderParams()}
function filterValueKey(key,value){const type=FIELD_MAP[key]?.type;if(value===null||value===undefined||value==='')return'__BLANK__';if(type==='boolean')return value?'true':'false';return String(value)}
function filterValueLabel(key,value){const type=FIELD_MAP[key]?.type;if(value===null||value===undefined||value==='')return'(空白)';if(type==='boolean')return value?'上架':'下架';if(type==='percent')return(n(value)*100).toFixed(1)+'%';if(type==='number')return formatInteger(value);return String(value)}
function matchesColumnFilter(p,key,filter){
  if(!filter)return true;
  const type=FIELD_MAP[key]?.type,value=p[key];
  if(Array.isArray(filter.selected)&&filter.selected.length&&!filter.selected.includes(filterValueKey(key,value)))return false;
  if(type==='number'||type==='percent'){
    const numeric=Number(value),min=filter.min===''||filter.min===undefined?null:Number(filter.min),max=filter.max===''||filter.max===undefined?null:Number(filter.max);
    if(!Number.isFinite(numeric))return min===null&&max===null;
    const compared=type==='percent'?numeric*100:numeric;
    return(min===null||compared>=min)&&(max===null||compared<=max);
  }
  if(type==='boolean')return true;
  return!filter.text||String(value??'').toLowerCase().includes(String(filter.text).toLowerCase());
}
function compareValues(a,b,key){const type=FIELD_MAP[key]?.type,av=a[key],bv=b[key];if(type==='number'||type==='percent')return(n(av)-n(bv));if(type==='boolean')return Number(!!av)-Number(!!bv);return String(av??'').localeCompare(String(bv??''),'zh-Hant',{numeric:true,sensitivity:'base'})}
function filtered(){
  const q=$('searchInput').value.trim().toLowerCase(),status=$('statusFilter').value;
  const list=products.filter(p=>(status==='all'||String(!!p.active)===status)&&(!q||[p.specManagementId,p.productManagementId,p.title,p.spec1,p.spec2,p.spec3,p.note,p.storeCode,p.storeName].some(v=>String(v||'').toLowerCase().includes(q)))&&Object.entries(columnFilters).every(([key,filter])=>matchesColumnFilter(p,key,filter)));
  if(sortState.key)list.sort((a,b)=>compareValues(a,b,sortState.key)*(sortState.direction==='asc'?1:-1));
  return list;
}
function renderAll(){renderTable();const list=filtered();$('statProducts').textContent=formatInteger(list.length);$('statActive').textContent=formatInteger(list.filter(p=>p.active).length);const margins=list.map(p=>p.profitRate).filter(Number.isFinite);$('statMargin').textContent=margins.length?(margins.reduce((a,b)=>a+b,0)/margins.length*100).toFixed(1)+'%':'0%';$('statUnits').textContent=formatInteger(list.reduce((s,p)=>s+n(p.unitsSold),0));updateSelectionCount()}
function getUniqueFilterValues(key){const map=new Map();products.forEach(p=>{const raw=p[key],k=filterValueKey(key,raw);if(!map.has(k))map.set(k,raw)});return[...map.entries()].sort((a,b)=>compareValues({[key]:a[1]},{[key]:b[1]},key)).slice(0,500)}
function renderTable(){
  const list=filtered(),pages=Math.max(1,Math.ceil(list.length/PAGE_SIZE));page=Math.min(page,pages);
  const rows=list.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);
  const columns=currentView==='sales'?SALES_COLUMNS:visibleColumns;
  const headerCheckbox=currentView==='products'?`<th class="select-cell"><input id="selectPageCheckbox" type="checkbox" title="選取本頁" ${rows.length&&rows.every(p=>selectedProductIds.has(p.id))?'checked':''}></th>`:'';
  $('tableHead').innerHTML='<tr class="column-title-row">'+headerCheckbox+columns.map(k=>{const active=sortState.key===k,hasFilter=!!columnFilters[k]&&Object.values(columnFilters[k]).some(v=>Array.isArray(v)?v.length:v!==''&&v!==undefined);return`<th><div class="excel-header"><span>${esc(FIELD_MAP[k].label)}</span><button type="button" class="excel-filter-button ${active||hasFilter?'active':''}" data-filter-menu="${k}" title="排序與篩選">${active?(sortState.direction==='asc'?'▲':'▼'):'▼'}</button></div></th>`}).join('')+'<th>操作</th></tr>';
  $('tableBody').innerHTML=rows.map(p=>'<tr>'+(currentView==='products'?`<td class="select-cell"><input type="checkbox" data-select-product="${p.id}" ${selectedProductIds.has(p.id)?'checked':''}></td>`:'')+columns.map(k=>`<td>${format(k,p[k])}</td>`).join('')+`<td class="action-cell"><button data-edit="${p.id}">編輯</button><button class="secondary" data-delete="${p.id}">刪除</button></td></tr>`).join('');
  $('pageInfo').textContent=`第 ${page} / ${pages} 頁，共 ${list.length.toLocaleString('zh-TW')} 筆`;$('prevPage').disabled=page<=1;$('nextPage').disabled=page>=pages;
  $('addProductBtn').classList.toggle('hidden',currentView==='sales');
  $('columnBtn').classList.toggle('hidden',currentView==='sales');
}
function closeFilterMenu(){document.getElementById('excelFilterMenu')?.remove();activeFilterKey=''}
function openFilterMenu(key,anchor){closeFilterMenu();activeFilterKey=key;const type=FIELD_MAP[key]?.type,current=columnFilters[key]||{},values=getUniqueFilterValues(key),allKeys=values.map(([k])=>k),selected=Array.isArray(current.selected)&&current.selected.length?current.selected:allKeys;const panel=document.createElement('div');panel.id='excelFilterMenu';panel.className='excel-filter-menu';panel.innerHTML=`<button type="button" data-menu-sort="asc">⬆ 升冪排序</button><button type="button" data-menu-sort="desc">⬇ 降冪排序</button><button type="button" data-menu-clear-sort>清除排序</button><hr>${type==='number'||type==='percent'?`<div class="excel-range"><input type="number" step="any" data-menu-min placeholder="最小值" value="${esc(current.min??'')}"><span>～</span><input type="number" step="any" data-menu-max placeholder="最大值" value="${esc(current.max??'')}"></div>`:`<input class="excel-value-search" type="search" data-menu-search placeholder="搜尋文字或項目" value="${esc(current.text??'')}">`}<label class="excel-check-all"><input type="checkbox" data-menu-all ${selected.length===allKeys.length?'checked':''}>（全選）</label><div class="excel-value-list">${values.map(([valueKey,raw])=>`<label data-value-label="${esc(filterValueLabel(key,raw).toLowerCase())}"><input type="checkbox" data-menu-value value="${esc(valueKey)}" ${selected.includes(valueKey)?'checked':''}>${esc(filterValueLabel(key,raw))}</label>`).join('')}</div>${values.length>=500?'<div class="muted excel-limit">僅顯示前 500 個項目</div>':''}<div class="excel-filter-actions"><button type="button" class="secondary" data-menu-clear>清除篩選</button><button type="button" data-menu-apply>套用</button></div>`;document.body.appendChild(panel);const rect=anchor.getBoundingClientRect();panel.style.left=Math.max(8,Math.min(rect.left,window.innerWidth-panel.offsetWidth-12))+'px';panel.style.top=Math.max(8,Math.min(rect.bottom+4,window.innerHeight-panel.offsetHeight-12))+'px'}
function updateSelectionCount(){$('selectionCount').textContent=`已選 ${selectedProductIds.size.toLocaleString('zh-TW')} 筆`}
function setView(view){currentView=view;page=1;closeFilterMenu();$('productTabBtn').classList.toggle('active',view==='products');$('salesTabBtn').classList.toggle('active',view==='sales');renderAll()}
function calculateDiscountProduct(p,discountPercent){
  const rate=Math.max(0,Math.min(100,n(discountPercent)))/100;
  const discountedPrice=Math.round(n(p.manualPriceTWD)*(1-rate));
  const customerShipping=discountedPrice>=params.freeShippingTWD?0:ceilKg(p.weightG)*params.customerShippingPerKgTWD;
  const gross=discountedPrice+customerShipping;
  const fee=discountedPrice*params.platformFeeRate;
  const profit=typeof p.fixedLogisticsCostTWD==='number'?gross-fee-n(p.fixedLogisticsCostTWD)-n(p.productCostTWD)-n(p.domesticShippingTWD):null;
  const margin=gross&&profit!==null?profit/gross:null;
  return {...p,discountPercent:rate,discountedPriceTWD:discountedPrice,discountedCustomerShippingTWD:customerShipping,discountedGrossTWD:gross,discountedPlatformFeeTWD:fee,discountedProfitTWD:profit,discountedProfitRate:margin};
}
function renderDiscountResults(){
  const percent=n($('discountPercent').value);const selected=products.filter(p=>selectedProductIds.has(p.id));discountResults=selected.map(p=>calculateDiscountProduct(p,percent));
  $('discountTableBody').innerHTML=discountResults.map(r=>`<tr><td>${esc(r.specManagementId||'')}</td><td>${esc(r.title||'')}</td><td>${formatInteger(r.manualPriceTWD)}</td><td>${formatInteger(r.discountedPriceTWD)}</td><td>${r.discountedProfitTWD===null?'':formatInteger(r.discountedProfitTWD)}</td><td>${r.discountedProfitRate===null?'':(r.discountedProfitRate*100).toFixed(1)+'%'}</td></tr>`).join('');
  const valid=discountResults.filter(r=>Number.isFinite(r.discountedProfitRate));const avg=valid.length?valid.reduce((s,r)=>s+r.discountedProfitRate,0)/valid.length:0;const negative=discountResults.filter(r=>n(r.discountedProfitTWD)<0).length;
  $('discountSummary').innerHTML=`<span>試算商品<strong>${formatInteger(discountResults.length)}</strong></span><span>折扣<strong>${percent.toFixed(1)}%</strong></span><span>平均折後利潤率<strong>${(avg*100).toFixed(1)}%</strong></span><span>負利潤商品<strong>${formatInteger(negative)}</strong></span>`;
}
function openDiscountDialog(){if(!selectedProductIds.size)return toast('請先選取商品，或使用「選取全部篩選結果」');renderDiscountResults();$('discountDialog').showModal()}
function exportDiscountResults(){if(!discountResults.length)return toast('目前沒有試算結果');const rows=discountResults.map(r=>({'商品規格管理編號':r.specManagementId||'','商品管理編號':r.productManagementId||'','商品標題':r.title||'','折扣率':r.discountPercent,'原售價(TWD)':Math.round(n(r.manualPriceTWD)),'折扣後售價(TWD)':r.discountedPriceTWD,'折扣後客收運費(TWD)':r.discountedCustomerShippingTWD,'折扣後平台費(TWD)':Math.round(n(r.discountedPlatformFeeTWD)),'折扣後利潤(TWD)':r.discountedProfitTWD===null?'':Math.round(r.discountedProfitTWD),'折扣後利潤率':r.discountedProfitRate??''}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'折扣利潤試算');XLSX.writeFile(wb,`折扣利潤試算_${new Date().toISOString().slice(0,10)}.xlsx`)}

function renderColumns(){$('columnOptions').innerHTML=FIELDS.map(([k,l])=>`<label><input type="checkbox" value="${k}" ${visibleColumns.includes(k)?'checked':''}>${esc(l)}</label>`).join('')}
function renderProductForm(p={}){const computed=compute(p);$('productId').value=p.id||'';$('productDialogTitle').textContent=p.id?'編輯商品':'新增商品';const pd=p.platformData||{};const platformHtml=`<div class="platform-editor full-span"><h3>平台資料</h3>${PLATFORMS.map(x=>`<fieldset><legend>${x.name}</legend><label><input type="checkbox" name="platform_${x.id}_enabled" ${pd[x.id]?.enabled?'checked':''}> 啟用此平台</label><label>售價<input type="number" step="any" name="platform_${x.id}_price" value="${esc(pd[x.id]?.price??'')}"></label><label>上架<select name="platform_${x.id}_active"><option value="true" ${pd[x.id]?.active!==false?'selected':''}>上架</option><option value="false" ${pd[x.id]?.active===false?'selected':''}>下架</option></select></label><label>備註<textarea name="platform_${x.id}_note">${esc(pd[x.id]?.note??'')}</textarea></label></fieldset>`).join('')}</div>`;$('productFields').innerHTML=platformHtml+FIELDS.filter(([k])=>!['conversionRate','storeCode','storeName','domesticShippingJPY'].includes(k)).map(([k,l,t,mode])=>{const v=computed[k]??'';if(k==='active')return`<label>${l}<select name="${k}"><option value="true" ${v!==false?'selected':''}>上架</option><option value="false" ${v===false?'selected':''}>下架</option></select></label>`;if(t==='textarea')return`<label>${l}<textarea name="${k}">${esc(v)}</textarea></label>`;const readonly=mode==='calculated'&&k==='logisticsMethod';const inputType=t==='number'||t==='percent'?'number':t==='url'?'url':'text';const step=t==='percent'?'0.0001':'any';const input=`<input name="${k}" type="${inputType}" step="${step}" value="${esc(v)}" ${readonly?'readonly':''}>`;if(mode==='calculated'&&!readonly)return`<label>${l}<span class="override-row">${input}<button type="button" class="secondary reset-override" data-reset="${k}">自動</button></span></label>`;return`<label>${l}${input}</label>`}).join('')}
function renderParams(){$('paramsFields').innerHTML=PARAM_DEFS.map(([k,l])=>`<label>${l}<input name="${k}" type="number" step="any" value="${params[k]}"></label>`).join('');$('shippingTierBody').innerHTML=params.tiers.map((t,i)=>`<tr><td><input name="tierMax_${i}" type="number" step="any" value="${t[0]}"></td><td><input name="tierFee_${i}" type="number" step="any" value="${t[1]}"></td></tr>`).join('')}
async function saveProduct(form){const fd=new FormData(form),id=$('productId').value,old=id?products.find(p=>p.id===id):{};const data={...old,overrides:{...(old?.overrides||{})}};FIELDS.forEach(([k,,t,mode])=>{if(['conversionRate','storeCode','storeName','domesticShippingJPY'].includes(k))return;const raw=fd.get(k);if(raw===null)return;data[k]=t==='number'||t==='percent'?(raw===''?null:Number(raw)):t==='boolean'?raw==='true':String(raw);if(mode==='calculated'&&k!=='logisticsMethod'&&raw!=='')data.overrides[k]=true});data.taiwanUrl=validUrl(data.taiwanUrl);data.japanUrl=validUrl(data.japanUrl);data.platformData={};PLATFORMS.forEach(x=>{data.platformData[x.id]={enabled:fd.get(`platform_${x.id}_enabled`)==='on',price:fd.get(`platform_${x.id}_price`)===''?null:Number(fd.get(`platform_${x.id}_price`)),active:fd.get(`platform_${x.id}_active`)==='true',note:String(fd.get(`platform_${x.id}_note`)||'')}});data.title=String(data.title||'').slice(0,100);data.updatedAt=serverTimestamp();if(!id)data.createdAt=serverTimestamp();const ref=id?doc(db,'products',id):doc(collection(db,'products'));await setDoc(ref,data,{merge:true});toast('商品已儲存');$('productDialog').close();await loadAll()}
function findHeader(row,aliases){const normalized=Object.fromEntries(Object.keys(row).map(k=>[cleanHeader(k),k]));for(const a of aliases){const hit=normalized[cleanHeader(a)];if(hit!==undefined)return hit}return null}
function normalizeImportRows(rows){let parent={productManagementId:'',title:'',note:'',taiwanUrl:'',japanUrl:''};return rows.map(row=>{const data={};for(const [key,aliases] of Object.entries(IMPORT_ALIASES)){const h=findHeader(row,aliases);if(h!==null)data[key]=row[h]}for(const k of Object.keys(data))data[k]=typeof data[k]==='string'?cleanText(data[k]):data[k];for(const k of ['productManagementId','title','note','taiwanUrl','japanUrl']){if(cleanText(data[k]))parent[k]=data[k];else data[k]=parent[k]}data.specManagementId=cleanText(data.specManagementId);data.productManagementId=cleanText(data.productManagementId);data.taiwanUrl=validUrl(data.taiwanUrl);data.japanUrl=validUrl(data.japanUrl);return data}).filter(r=>r.specManagementId)}
async function exportProducts(){const rows=products.map(p=>{const r={};FIELDS.forEach(([k,l])=>r[l]=p[k]??'');PLATFORMS.forEach(x=>{const d=p.platformData?.[x.id]||{};r[`${x.name}-啟用`]=!!d.enabled;r[`${x.name}-售價`]=d.price??'';r[`${x.name}-上架`]=d.active!==false;r[`${x.name}-備註`]=d.note??''});return r});const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'商品主檔');XLSX.writeFile(wb,`商品資料庫_${new Date().toISOString().slice(0,10)}.xlsx`)}
async function importExcel(){const file=$('excelFile').files[0];if(!file)return toast('請先選擇 Excel 或 CSV 檔案');$('importBtn').disabled=true;$('importStatus').textContent='讀取中…';try{const buf=await file.arrayBuffer(),wb=XLSX.read(buf,{type:'array'}),preferred=wb.SheetNames.find(x=>x.toLowerCase()==='model')||wb.SheetNames[0];const raw=XLSX.utils.sheet_to_json(wb.Sheets[preferred],{defval:'',raw:false});const rows=normalizeImportRows(raw);if(!rows.length)throw new Error('找不到有效的商品規格管理編號');const existing=new Map(products.filter(p=>p.specManagementId).map(p=>[cleanText(p.specManagementId),p]));let done=0,skipped=raw.length-rows.length;for(let start=0;start<rows.length;start+=400){const batch=writeBatch(db);for(const row of rows.slice(start,start+400)){const selectedPlatform=$('importPlatform').value,data={active:true,overrides:{},platformData:{[selectedPlatform]:{enabled:true,active:true,price:null,note:''}},...row};data.priceJPY=cleanNumber(data.priceJPY);data.weightG=cleanNumber(data.weightG);data.pageViews=n(cleanNumber(data.pageViews));data.unitsSold=n(cleanNumber(data.unitsSold));data.orderCount=n(cleanNumber(data.orderCount));const key=cleanText(data.specManagementId),old=existing.get(key);if(old&&$('importMode').value==='skip'){skipped++;continue}const ref=old?doc(db,'products',old.id):doc(collection(db,'products'));const merged=old?{...data,active:old.active??true,note:data.note||old.note||'',overrides:old.overrides||{},platformData:{...(old.platformData||{}),...(data.platformData||{})},updatedAt:serverTimestamp()}:{...data,createdAt:serverTimestamp(),updatedAt:serverTimestamp()};batch.set(ref,merged,{merge:true});done++}await batch.commit()}await addDoc(collection(db,'imports'),{type:'products',fileName:file.name,rowCount:raw.length,successCount:done,skippedCount:skipped,createdAt:serverTimestamp()});$('importStatus').textContent=`完成：${done} 筆，略過 ${skipped} 筆`;toast('商品匯入完成');await loadAll()}catch(e){console.error(e);$('importStatus').textContent='匯入失敗：'+e.message}finally{$('importBtn').disabled=false}}

function renderStores(){const q=cleanText($('storeSearch').value).toLowerCase();const list=stores.filter(s=>!q||[s.code,s.name,s.url,s.shippingJPY].some(v=>String(v||'').toLowerCase().includes(q)));$('storeTableBody').innerHTML=list.map(s=>`<tr><td>${esc(s.code)}</td><td>${esc(s.name||'')}</td><td>${format('japanUrl',s.url)}</td><td>${esc(s.shippingJPY??params.domesticShippingJPY)}</td><td class="action-cell"><button type="button" data-store-edit="${esc(s.id)}">編輯</button><button type="button" class="secondary" data-store-delete="${esc(s.id)}">刪除</button></td></tr>`).join('');$('storeCount').textContent=`共 ${list.length} 間店鋪`}
function openStoreForm(store={}){$('storeId').value=store.id||'';$('storeCode').value=store.code||'';$('storeName').value=store.name||'';$('storeUrl').value=store.url||'';$('storeShipping').value=store.shippingJPY??params.domesticShippingJPY;$('storeFormTitle').textContent=store.id?'編輯店鋪':'新增店鋪';$('storeEditDialog').showModal()}
async function saveStore(form){const fd=new FormData(form),id=$('storeId').value,code=cleanText(fd.get('code')).toUpperCase();if(!/^R\d{1,4}$/i.test(code))return toast('店鋪編號格式需為 R 加數字，例如 R60');const data={code,name:cleanText(fd.get('name')),url:validUrl(fd.get('url')),shippingJPY:n(fd.get('shippingJPY'))||params.domesticShippingJPY,updatedAt:serverTimestamp()};if(!id)data.createdAt=serverTimestamp();await setDoc(doc(db,'stores',id||code),data,{merge:true});$('storeEditDialog').close();await loadAll();renderStores();toast('店鋪已儲存')}
async function importStores(){const file=$('storeExcelFile').files[0];if(!file)return toast('請先選擇店鋪 Excel');$('storeImportStatus').textContent='讀取中…';try{const wb=XLSX.read(await file.arrayBuffer(),{type:'array'}),merged=new Map();for(const sheetName of wb.SheetNames){const rows=XLSX.utils.sheet_to_json(wb.Sheets[sheetName],{defval:'',raw:false});for(const row of rows){const code=cleanText(row['樂天編號']||row['店鋪編號']||row['編號']).toUpperCase();if(!code)continue;const old=merged.get(code)||{};merged.set(code,{code,name:cleanText(row['店家名']||row['店鋪名']||row['店鋪名稱']||old.name),url:validUrl(row['網址']||row['店鋪網址']||old.url),shippingJPY:cleanNumber(row['運費'])??old.shippingJPY??params.domesticShippingJPY})}}if(!merged.size)throw new Error('找不到「樂天編號」欄位');const list=[...merged.values()];for(let i=0;i<list.length;i+=400){const batch=writeBatch(db);list.slice(i,i+400).forEach(s=>batch.set(doc(db,'stores',s.code),{...s,updatedAt:serverTimestamp()},{merge:true}));await batch.commit()}await addDoc(collection(db,'imports'),{type:'stores',fileName:file.name,rowCount:list.length,successCount:list.length,createdAt:serverTimestamp()});$('storeImportStatus').textContent=`完成：${list.length} 間店鋪`;await loadAll();renderStores();toast('店鋪總表匯入完成')}catch(e){console.error(e);$('storeImportStatus').textContent='匯入失敗：'+e.message}}
async function resyncProducts(){await loadAll();renderStores();toast(`已依 ${stores.length} 間店鋪重新計算 ${products.length} 筆商品`)}
async function countCollection(name){const s=await getDocs(collection(db,name));return s.size}
async function refreshMaintenance(){const entries=await Promise.all(Object.entries(MAINT_COLLECTIONS).map(async([k,l])=>[k,l,await countCollection(k)]));$('maintenanceCounts').innerHTML=entries.map(([k,l,c])=>`<label class="maintenance-row"><input type="checkbox" value="${k}"><span>${l}</span><strong>${c}</strong></label>`).join('');await runHealthCheck(false)}
function productKeys(){const s=new Set();products.forEach(p=>[p.specManagementId,p.productManagementId].forEach(v=>{if(cleanText(v))s.add(cleanText(v))}));return s}
function recordProductKey(d){for(const k of ['商品規格管理編號','商品管理編號','specManagementId','productManagementId','sku','SKU','商品編號'])if(cleanText(d[k]))return cleanText(d[k]);return''}
async function runHealthCheck(showToast=true){const keys=productKeys(),result={};for(const name of ['sales','ads','productAnalysis']){const snap=await getDocs(collection(db,name));let unmatched=0;snap.forEach(x=>{const key=recordProductKey(x.data());if(!key||!keys.has(key))unmatched++});result[name]=unmatched}$('healthSales').textContent=result.sales;$('healthAds').textContent=result.ads;$('healthAnalysis').textContent=result.productAnalysis;if(showToast)toast('商品對應健康檢查完成');return result}
async function deleteCollection(name){const snap=await getDocs(collection(db,name));for(let i=0;i<snap.docs.length;i+=450){const batch=writeBatch(db);snap.docs.slice(i,i+450).forEach(d=>batch.delete(d.ref));await batch.commit()}}
async function deleteSelectedCollections(){if($('deleteConfirm').value!=='DELETE')return toast('請輸入 DELETE 才能刪除');const selected=[...$('maintenanceCounts').querySelectorAll('input:checked')].map(x=>x.value);if(!selected.length)return toast('請先勾選資料');for(const c of selected)await deleteCollection(c);$('deleteConfirm').value='';await loadAll();await refreshMaintenance();toast('指定資料已刪除')}
async function clearImportedData(){if($('deleteConfirm').value!=='DELETE')return toast('請輸入 DELETE 才能刪除');for(const c of ['products','sales','ads','productAnalysis','imports','platforms','stores'])await deleteCollection(c);$('deleteConfirm').value='';await ensurePlatforms();await loadAll();await refreshMaintenance();toast('全部匯入資料已清空；登入帳號未變更')}
async function rebuildProductIndex(){await deleteCollection('productIndex');for(let i=0;i<products.length;i+=400){const batch=writeBatch(db);products.slice(i,i+400).forEach(p=>{for(const[type,key]of[['spec',p.specManagementId],['product',p.productManagementId]])if(cleanText(key)){const id=encodeURIComponent(`${type}_${cleanText(key)}`).replaceAll('%','_');batch.set(doc(db,'productIndex',id),{type,key:cleanText(key),productId:p.id,updatedAt:serverTimestamp()})}});await batch.commit()}toast(`商品索引重建完成：${products.length} 筆商品`)}
async function recalcDashboard(){const health=await runHealthCheck(false);const sales=await countCollection('sales'),ads=await countCollection('ads'),analysis=await countCollection('productAnalysis');await setDoc(doc(db,'settings','dashboardSummary'),{productCount:products.length,activeCount:products.filter(p=>p.active).length,totalUnits:products.reduce((s,p)=>s+n(p.unitsSold),0),salesCount:sales,adsCount:ads,analysisCount:analysis,unmatched:health,updatedAt:serverTimestamp()});toast('Dashboard 已重新計算')}

$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginError').textContent='';try{await signInWithEmailAndPassword(auth,$('loginEmail').value,$('loginPassword').value)}catch(err){$('loginError').textContent='登入失敗：'+err.message}});
$('logoutBtn').onclick=()=>signOut(auth);$('searchInput').oninput=()=>{page=1;renderAll()};$('statusFilter').onchange=()=>{page=1;renderAll()};$('prevPage').onclick=()=>{page--;renderTable()};$('nextPage').onclick=()=>{page++;renderTable()};
$('tableHead').addEventListener('click',e=>{const btn=e.target.closest('[data-filter-menu]');if(!btn)return;e.stopPropagation();openFilterMenu(btn.dataset.filterMenu,btn)});
document.addEventListener('click',e=>{const panel=e.target.closest('#excelFilterMenu');if(!panel){closeFilterMenu();return}e.stopPropagation();const key=activeFilterKey;if(e.target.closest('[data-menu-sort]')){sortState={key,direction:e.target.closest('[data-menu-sort]').dataset.menuSort};page=1;renderAll();closeFilterMenu();return}if(e.target.closest('[data-menu-clear-sort]')){if(sortState.key===key)sortState={key:'',direction:'asc'};renderAll();closeFilterMenu();return}if(e.target.matches('[data-menu-all]')){panel.querySelectorAll('[data-menu-value]').forEach(x=>x.checked=e.target.checked);return}if(e.target.closest('[data-menu-clear]')){delete columnFilters[key];page=1;renderAll();closeFilterMenu();return}if(e.target.closest('[data-menu-apply]')){const selected=[...panel.querySelectorAll('[data-menu-value]:checked')].map(x=>x.value),allCount=panel.querySelectorAll('[data-menu-value]').length,next={selected:selected.length===allCount?[]:selected};const min=panel.querySelector('[data-menu-min]'),max=panel.querySelector('[data-menu-max]'),search=panel.querySelector('[data-menu-search]');if(min)next.min=min.value;if(max)next.max=max.value;if(search)next.text=search.value;columnFilters[key]=next;page=1;renderAll();closeFilterMenu()}});
document.addEventListener('input',e=>{if(!e.target.matches('#excelFilterMenu [data-menu-search]'))return;const q=e.target.value.toLowerCase();e.target.closest('#excelFilterMenu').querySelectorAll('[data-value-label]').forEach(label=>label.classList.toggle('hidden',!label.dataset.valueLabel.includes(q)))});
$('clearColumnFiltersBtn').onclick=()=>{columnFilters={};sortState={key:'',direction:'asc'};page=1;renderAll()};
$('productTabBtn').onclick=()=>setView('products');$('salesTabBtn').onclick=()=>setView('sales');$('selectFilteredBtn').onclick=()=>{filtered().forEach(p=>selectedProductIds.add(p.id));renderTable();updateSelectionCount();toast('已選取全部篩選結果')};$('clearSelectionBtn').onclick=()=>{selectedProductIds.clear();renderTable();updateSelectionCount()};$('discountCalcBtn').onclick=openDiscountDialog;$('recalcDiscountBtn').onclick=renderDiscountResults;$('discountPercent').oninput=renderDiscountResults;$('exportDiscountBtn').onclick=exportDiscountResults;
$('addProductBtn').onclick=()=>{renderProductForm({active:true});$('productDialog').showModal()};$('productForm').addEventListener('submit',async e=>{e.preventDefault();await saveProduct(e.currentTarget)});
$('productFields').addEventListener('click',e=>{const k=e.target.dataset.reset;if(!k)return;const input=e.target.closest('label').querySelector(`[name="${k}"]`);input.value=''});
$('tableBody').addEventListener('change',e=>{const id=e.target.dataset.selectProduct;if(!id)return;e.target.checked?selectedProductIds.add(id):selectedProductIds.delete(id);updateSelectionCount()});
$('tableHead').addEventListener('change',e=>{if(e.target.id!=='selectPageCheckbox')return;const list=filtered().slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);list.forEach(p=>e.target.checked?selectedProductIds.add(p.id):selectedProductIds.delete(p.id));renderTable();updateSelectionCount()});
$('tableBody').addEventListener('click',async e=>{const id=e.target.dataset.edit||e.target.dataset.delete;if(!id)return;if(e.target.dataset.edit){renderProductForm(products.find(p=>p.id===id));$('productDialog').showModal()}else if(confirm('確定刪除此商品？')){await deleteDoc(doc(db,'products',id));await loadAll();toast('已刪除')}});
$('openParamsBtn').onclick=()=>$('paramsDialog').showModal();$('paramsForm').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),next={};PARAM_DEFS.forEach(([k])=>next[k]=Number(fd.get(k)));next.tiers=params.tiers.map((_,i)=>[Number(fd.get(`tierMax_${i}`)),Number(fd.get(`tierFee_${i}`))]).sort((a,b)=>a[0]-b[0]);await setDoc(doc(db,'settings','params'),{...next,updatedAt:serverTimestamp()});params={...params,...next};$('paramsDialog').close();await loadAll();toast('參數已更新')});
$('columnBtn').onclick=()=>{renderColumns();$('columnsDialog').showModal()};$('columnOptions').addEventListener('change',()=>{visibleColumns=[...$('columnOptions').querySelectorAll('input:checked')].map(x=>x.value);localStorage.setItem('visibleColumns',JSON.stringify(visibleColumns));renderTable()});$('selectDefaultColumns').onclick=()=>{visibleColumns=[...DEFAULT_COLUMNS];localStorage.setItem('visibleColumns',JSON.stringify(visibleColumns));renderColumns();renderTable()};
$('importBtn').onclick=importExcel;$('exportBtn').onclick=exportProducts;
$('storeManagerBtn').onclick=()=>{renderStores();$('storesDialog').showModal()};$('storeSearch').oninput=renderStores;$('addStoreBtn').onclick=()=>openStoreForm();$('storeForm').addEventListener('submit',async e=>{e.preventDefault();await saveStore(e.currentTarget)});$('storeImportBtn').onclick=importStores;$('resyncStoresBtn').onclick=resyncProducts;
$('storeTableBody').addEventListener('click',async e=>{const edit=e.target.dataset.storeEdit,del=e.target.dataset.storeDelete;if(edit)openStoreForm(stores.find(s=>s.id===edit));if(del&&confirm('確定刪除此店鋪？未指定店鋪的商品將改用預設運費。')){await deleteDoc(doc(db,'stores',del));await loadAll();renderStores();toast('店鋪已刪除')}});
$('maintenanceBtn').onclick=async()=>{$('maintenanceDialog').showModal();await refreshMaintenance()};$('deleteSelectedBtn').onclick=deleteSelectedCollections;$('clearAllBtn').onclick=clearImportedData;$('rebuildIndexBtn').onclick=rebuildProductIndex;$('recalcDashboardBtn').onclick=recalcDashboard;$('healthCheckBtn').onclick=()=>runHealthCheck(true);$('resyncMaintenanceBtn').onclick=resyncProducts;
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
onAuthStateChanged(auth,async user=>{if(user){$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('userEmail').textContent=user.email;await loadAll()}else{$('appView').classList.add('hidden');$('loginView').classList.remove('hidden')}});
